### PR TITLE
[#75] Change Pagination Behavior to Move Along with User

### LINKED ISSUE #75: Change Pagination Behavior to Move Along with User
**Description**:

Change pagination indicator's behavior to move along with user scrolling down/up page.

Currently, pagination indicator is always in the top of the page. It will be better to make pagination indicator move as user scroll down/up the pages.

Screenshot 2023-05-02 at 4 53 33 PM

Example: [Terraform Tutorial: Provision an EKS Cluster (AWS)](https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks)

Screenshot 2023-05-02 at 4 57 41 PM

**Why**:

It is hard for user to navigate to specific section in the middle of the page while pagination indicator is not following user's scrolled page position.

### PR DESCRIPTION
**Pull request by vitran12**
#### What this PR does / why we need it?
- Fixes #75

https://github.com/yorkie-team/yorkie-team.github.io/assets/150248298/5c5ea7de-cc1d-4673-81d7-64b965a30d37

### CODE REVIEW

**Review by hackerwins — CHANGES_REQUESTED** [review]
Thanks for your contribution.

I fetched this branch and then tested it. In the test I found some regression errors in the test.

A. Responsive layouts are broken on some pages

Broken pages:
- `/docs/getting-started/with-js-sdk`
- `/docs/getting-started/with-ios-sdk`
- `/docs/js-sdk`

Normal pages:
- `/docs/self-hosted-server`
- `/docs/internals`

chrome-capture-2023-10-14 (1)

B. The sidebar and content overlap.

Screenshot 2023-11-14 at 9 41 19 AM

**Comment by vitran12** [comment]
> Thanks for your contribution.
> 
> I fetched this branch and then tested it. In the test I found some regression errors in the test.
> 
> A. Responsive layouts are broken on some pages
> 
> Broken pages:
> 
> * `/docs/getting-started/with-js-sdk`
> * `/docs/getting-started/with-ios-sdk`
> * `/docs/js-sdk`
> 
> Normal pages:
> 
> * `/docs/self-hosted-server`
> * `/docs/internals`
> 
> chrome-capture-2023-10-14 (1) [ chrome-capture-2023-10-14 (1) ](https://user-images.githubusercontent.com/2059311/282629169-1baecbc5-aa2f-4372-b89f-4b4dd07a505c.gif) [ ](https://user-images.githubusercontent.com/2059311/282629169-1baecbc5-aa2f-4372-b89f-4b4dd07a505c.gif)
> 
> B. The sidebar and content overlap.
> 
> Screenshot 2023-11-14 at 9 41 19 AM

Thank you for your review. I sync pages.

**Review by hackerwins — APPROVED** [review]
LGTM.

**Comment by krapie** [comment]
Wow! thank you for your contribution!
LGTM @vitran12!

**Pull request merged**
