### PR TITLE
Update Docs:CLI related with Account Management

### PR DESCRIPTION
**Pull request by sigmaith**
#### What this PR does / why we need it?
I have updated the CLI command information documentation following the changes related to the user-related CLI in yorkie-team/yorkie.

#### Any background context you want to provide?
This is related to this issue. https://github.com/yorkie-team/yorkie/pull/983

#### What are the relevant tickets?

Fixes #

### Checklist
- [x] Added relevant tests or not required
- [x] Didn't break anything

## Summary by CodeRabbit

- **New Features**
	- Updated the command syntax for logging into the server using the Yorkie CLI, enhancing security by prompting for the password interactively.
	- Introduced new commands for changing the password and deleting the account.
	- Updated the logout command to align with the new command structure.

- **Documentation**
	- Improved clarity in documentation regarding the new login command, account creation, and security practices.

### CODE REVIEW

**Review by chacha912 — COMMENTED** [review]
Thanks for your contribution. Please check the comments below.

1. The command `$ yorkie logout` should be updated to `$ yorkie user logout`.
2. Please include usage instructions for the following commands:
   - `yorkie user delete-account -u <username>`
   - `yorkie user change-password -u <username>`
3. Ensure proper spacing throughout the documentation to improve readability.

**Comment by hackerwins** [comment]
@sigmaith Could you sign up the CLA?

**Comment by sigmaith** [comment]
Oh, I missed it. I just signed it!

**Comment by hackerwins** [comment]
@sigmaith 
In the last commit, the interface was changed by removing user. Can you reflect this in the document?
https://github.com/yorkie-team/yorkie/commit/dffc44c082b126a30a0767bd911aa8cded3b9dbf

**Comment by sigmaith** [comment]
Thank you for mention. I'll do it.

**Review by hackerwins — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
